name: petroleum_management_system
description: A Flutter application for monitoring Petroleum Management Systems in Gas Stations in Talibon, Bohol, Philippines.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  percent_indicator: ^4.2.2
  fl_chart: ^0.70.0
  intl: ^0.18.0
  provider: ^6.0.5
  url_launcher: ^6.1.7
  image_picker: ^0.8.7+4
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^5.0.0
  flutter_local_notifications: ^17.0.0
  permission_handler: ^10.4.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/assets/1.jpg
    - lib/assets/2.jpg